version: '3'

services:
  youtrack-nginx:
    container_name: ${CONTAINER_YOUTRACK_NGINX_NAME}
    image: 'nginx:alpine'
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  youtrack:
    container_name: ${CONTAINER_YOUTRACK_NAME}
    image: 'jetbrains/youtrack:2018.3.47247'
    restart: unless-stopped
    volumes:
      - ${YT_DATA}:/opt/youtrack/data:rw
      - ${YT_CONF}:/opt/youtrack/conf:rw
      - ${YT_LOGS}:/opt/youtrack/logs:rw
      - ${YT_BACKUPS}:/opt/youtrack/backups:rw

networks:
  default:
    external:
      name: ${NETWORK}
