version: '3'

services:
  youtrack:
    container_name: ${CONTAINER_YOUTRACK_NAME}
    image: 'jetbrains/youtrack:2018.3.47247'
    restart: unless-stopped
    volumes:
      - ${YT_DATA}:/opt/youtrack/data:rw
      - ${YT_CONF}:/opt/youtrack/conf:rw
      - ${YT_LOGS}:/opt/youtrack/logs:rw
      - ${YT_BACKUPS}:/opt/youtrack/backups:rw
    ports:
      # the mapped port must match ssh_port specified below.
      - "${EXTERNAL_SSH_PORT}:8080"
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: ${NETWORK}
